version: '3'
services:
  os:
    container_name: ide
    hostname: ide
    build: .
    ports:
    - "2222:22"     # ssh
    - "5000:5000"   # test app
    privileged: true
    links:
    - mysql
    volumes:
    - ~/notes:/home/$USER/notes
    - ~/.aws:/home/$USER/.aws
    - ~/.config:/home/$USER/.config
    - ~/.ccloud:/home/$USER/.ccloud
    - ~/.gnupg:/home/$USER/.gnupg
    - ~/.kioskconfig:/home/$USER/.kioskconfig
    - ~/.m2:/home/$USER/.m2
    - ~/.netrc:/home/$USER/.netrc
    - ~/.pypirc:/home/$USER/.pypirc
    - ~/.ssh:/home/$USER/.ssh
    - workspace:/home/$USER/workspace
    - virtualenvs:/home/$USER/.virtualenvs
    - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - database:/var/lib/mysql
volumes:
  database: {}
  virtualenvs: {}
  workspace: {}
