version: '3'
services:
  os:
    container_name: ide
    hostname: ide
    build: .
    ports:
    - "2222:22"     # ssh
    - "5000:5000"   # test app
    privileged: true
    links:
    - mysql
    volumes:
    - ~/notes:$H2/notes
    - ~/.aws:$H2/.aws
    - ~/.config:$H2/.config
    - ~/.ccloud:$H2/.ccloud
    - ~/.gnupg:$H2/.gnupg
    - ~/.kioskconfig:$H2/.kioskconfig
    - ~/.pip:$H2/.pip
    - ~/.pypirc:$H2/.pypirc
    - ~/.ssh:$H2/.ssh
    - ~/.xonshrc:$H2/.xonshrc
    - workspace:$H2/workspace
    - virtualenvs:$H2/.virtualenvs
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - database:/var/lib/mysql
  cron:
    container_name: cron
    hostname: cron
    build: cron
    depends_on:
    - os
    privileged: true
    volumes:
    - workspace:$H2/workspace
volumes:
  database: {}
  virtualenvs: {}
  workspace: {}
